In [2]:
import tensorflow as tf
tf.__version__

'2.1.0'

#### 创建数据类型

In [3]:
a=tf.constant([1,3],dtype=tf.int64)
print(a)
print(a.dtype)
print(a.shape)

tf.Tensor([1 3], shape=(2,), dtype=int64)
<dtype: 'int64'>
(2,)


##### numpy格式转化成tensor

In [4]:
import numpy as np
a=np.arange(0,5)
b=tf.convert_to_tensor(a,dtype=tf.int64)
print(a)
print(b)

[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)


##### 创建tensor的方法

In [6]:
a=tf.zeros([2,3])
b=tf.ones([3,3])
c=tf.fill([2,2],9)
print(a)
print(b)
print(c)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[9 9]
 [9 9]], shape=(2, 2), dtype=int32)


- 生成初始化参数
 - 生成正态分布的随机函数，默认均值为0，标准差为1
   tf.random.normal(维度，mean=均值，stddev=标准差)
 - 生成截断式正态分布的随机函数
   tf.random.truncated_normal(维度，mean=均值，stddev=标准差)
 - 生成均匀分布随机函数
   tf.random.uniform(维度,minval=最小值，maxval=最大值)

In [9]:
d=tf.random.normal([2,2],mean=1,stddev=1)
print(d)
h=tf.random.truncated_normal([2,2],mean=1,stddev=1)
print(h)
g=tf.random.uniform([2,2],minval=1,maxval=3)
print(g)

tf.Tensor(
[[-0.7462357   1.8542514 ]
 [ 1.171151    0.70981777]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.2693284 1.2608747]
 [1.0530818 2.3834243]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2.6329389 2.1327388]
 [1.0652857 2.623557 ]], shape=(2, 2), dtype=float32)


##### 常用函数
- 强制tensor转化数据类型
  tf.cast(张量名，dtype=数据类型)
- 计算张量的最小值
  tf.reduce_min(张量名)
- 计算张量维度上元素的最大值
  tf.reduce_max(张量名)
- 计算张量沿着指定维度的平均值
  tf.reduce_mean(张量，axis=操作轴)
- 计算张量沿着指定维度的和
  tf.reduce_sum(张量，axis=操作轴)
  
- tf.Variable()将变量标记为“可训练”，被标记的变量会在反向传播中记录梯度信息。
  tf.Variable(初始化）

In [16]:
a=tf.constant([1,2,3,4],dtype=tf.int64)
print(a)
print(tf.cast(a,dtype=tf.float32))
print(tf.reduce_max(a))
print(tf.reduce_min(a))
print(tf.reduce_mean(a))
b=tf.random.uniform([3,3],maxval=5,minval=1)
print(b)
print(tf.reduce_max(b,axis=1))
print(tf.reduce_sum(b,axis=0))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(
[[4.4295278 1.6647477 1.1110783]
 [4.702087  4.9197555 1.5433707]
 [2.2885685 4.11473   3.3056374]], shape=(3, 3), dtype=float32)
tf.Tensor([4.4295278 4.9197555 4.11473  ], shape=(3,), dtype=float32)
tf.Tensor([11.420183  10.699233   5.9600863], shape=(3,), dtype=float32)


##### 常用的计算函数
- 四则运算：tf.add, tf.subtract, tf.multiply, tf.divide
- 平方、次方与开方：tf.square, tf.pow, tf.sqrt
- 矩阵相乘：tf.matmul

In [29]:
a=tf.ones([2,2],dtype=tf.float32)
b=tf.fill([2,2],4)
b=tf.cast(b,dtype=tf.float32)
print(a)
print(b)
print(tf.add(a,b))
print(tf.subtract(b,a))
print(tf.multiply(a,b))
print(tf.pow(b,2))
print(tf.sqrt(b))
print(tf.matmul(a,b))

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 5.]
 [5. 5.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3. 3.]
 [3. 3.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[16. 16.]
 [16. 16.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


##### 常见的函数
- 构建数据集 tf.data.Dataset.from_tensor_slices((数据特征，标签)) 该函数可以使用numpy格式也可以使用tensor格式

In [31]:
feature=tf.random.uniform([3,2],maxval=5,minval=1)
labels=tf.constant([1,0,0])
datasets=tf.data.Dataset.from_tensor_slices((feature,labels))
for ele in datasets:
    print(ele)

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.9200177, 2.4266734], dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.2549915, 2.505282 ], dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.5694127, 2.1554089], dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


##### 常见的函数
- tf.GradientTape 计算求导,使用with结构
- tf.one_hot(数据，depth=几分类)常用与分类问题
- tf.nn.softmax(x) 输出符合概率分布
- assign_sub常用于函数自更新
- tf.argmax(张量名，axis=？)用户返回张量的指定维度的最大索引

In [34]:
with tf.GradientTape() as tape:
    w=tf.Variable(tf.constant(3.0))
    loss=tf.pow(w,2)
grad=tape.gradient(loss,w)
print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)


In [36]:
classes=3
labels=tf.constant([1,0,2])
output=tf.one_hot(labels,depth=3)
print(output)

tf.Tensor(
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [39]:
h=tf.constant([1.,2.,3.,4.,5.])
print(tf.nn.softmax(h))

tf.Tensor([0.01165623 0.03168492 0.08612854 0.23412165 0.6364086 ], shape=(5,), dtype=float32)


In [40]:
w=tf.Variable(3)
w.assign_sub(1)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>


In [41]:
test=np.array([[1,2,3],[2,3,4],[5,6,7],[8,7,2]])
print(test)
print(tf.argmax(test,axis=1))
print(tf.argmax(test,axis=0))

[[1 2 3]
 [2 3 4]
 [5 6 7]
 [8 7 2]]
tf.Tensor([2 2 2 0], shape=(4,), dtype=int64)
tf.Tensor([3 3 2], shape=(3,), dtype=int64)
